# Generated by Django 3.2.6 on 2021-08-20 20:45

from django.db import migrations, models
import djongo.models.fields
import fernet_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(blank=True, max_length=60)),
                ('nomusuario', models.CharField(blank=True, max_length=25)),
                ('contrasenia', fernet_fields.fields.EncryptedTextField()),
                ('json_publicaciones', djongo.models.fields.JSONField(null=True)),
            ],
        ),
    ]
