# Generated by Django 3.2.6 on 2021-08-20 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('direccion', models.CharField(blank=True, max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=60)),
                ('ruta_publicacion', models.ImageField(null=True, upload_to='publicacion')),
            ],
        ),
    ]
